// W01/W02/S01, using the Make export's layout, typography, tokens and controls.
import { useState, useEffect, type ReactNode } from 'react'
import { api, dateTime, passed, type Project, type Checkpoint, type Config } from '../lib/api'
import { Button, StatusBadge, Wordmark, InlineNotice, FilePath } from './ui'
import { CodePlain, CodeUnavailable } from './CodeExcerpt'
import { ArrowLeft, ChevronRight, Refresh, Lock, Trash, Settings, Check } from '../lib/icons'

type Props = { route:string; navigate:(r:string)=>void; project:Project|null; history:Checkpoint[]; config:Config|null; busy:boolean;
  refresh:()=>void; onCheckpoint:(c:Checkpoint)=>void; onReceipt:(c:Checkpoint)=>void; onImport:()=>void; onSummary:(c:Checkpoint)=>void; onDelete:()=>void }

export function LiveWebsite(p: Props) {
  const cp = p.history.find(c=>c.id===p.route.split('/')[2])
  const rows = p.project ? p.history.filter(c=>c.project_id===p.project!.id && c.status!=='skipped') : []
  return <div className="min-h-full overflow-hidden rounded-[var(--radius-dialog)] border border-subtle bg-canvas text-primary">
    <header className="sticky top-0 z-10 border-b border-subtle bg-panel/85 backdrop-blur"><div className="mx-auto flex w-full max-w-[1120px] items-center justify-between gap-4 px-4 py-3 sm:px-6 md:px-8"><div className="flex items-center gap-3"><Wordmark size="sm"/><span className="hidden text-[13px] text-secondary sm:inline">· <span className="font-mono">{p.project?.name || 'No project'}</span> · {new Date().toLocaleDateString()}</span></div><span className="text-[12px] text-secondary">Private account</span></div></header>
    <main className="mx-auto w-full max-w-[1120px] px-4 py-8 sm:px-6 md:px-8">
      {p.route==='/settings' ? <SettingsView {...p}/> : cp ? <Evidence cp={cp} {...p}/> : p.route.split('/')[2] ? <InlineNotice kind="info">This evidence record is unavailable. <button onClick={()=>p.navigate('/history')} className="underline">Return to history</button></InlineNotice> : <div className="space-y-8">
        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div className="space-y-1.5"><h1 className="text-[28px] font-semibold leading-[36px]">Today’s session</h1><p className="text-[14px] text-secondary"><span className="font-mono">{p.project?.name || 'Choose a project to begin'}</span> · TypeScript / JavaScript</p></div><div className="flex items-center gap-2"><Button variant="secondary" onClick={()=>p.navigate('/')}>Open checkpoint</Button><button aria-label="Refresh history" onClick={p.refresh} className="rounded border border-subtle p-2"><Refresh size={16}/></button><button aria-label="Project settings" onClick={()=>p.navigate('/settings')} className="rounded border border-subtle p-2"><Settings size={16}/></button></div></div>
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-[14px] text-secondary"><span className="text-primary"><span className="font-semibold">{rows.filter(passed).length}</span> concepts demonstrated</span><span>·</span><span><span className="font-semibold text-primary">{rows.filter(c=>!passed(c)).length}</span> awaiting explanation</span></div>
        {p.busy && !rows.length ? <div role="status" className="space-y-3">{[1,2,3].map(n=><div key={n} className="h-20 animate-pulse rounded border border-subtle bg-panel"/>)}</div> : !rows.length ? <div className="rounded-[var(--radius-panel)] border border-subtle bg-panel px-6 py-12 text-center"><h2 className="text-[17px] font-medium">Your learning history starts with your first checkpoint.</h2><p className="my-3 text-[14px] text-secondary">Start a scoped coding session and explain an approved saved change.</p><Button onClick={()=>p.navigate('/')}>Start a session</Button></div> : <div className="space-y-3">{rows.map(c=><button key={c.id} onClick={()=>p.navigate('/history/'+c.id)} className="group flex w-full flex-wrap items-center gap-4 rounded-[var(--radius-panel)] border border-subtle bg-panel px-4 py-4 text-left transition-colors hover:border-control"><div className="min-w-0 flex-1 space-y-1"><div className="flex flex-wrap items-center gap-3"><span className="text-[15px] font-medium">{c.question?.concept || 'Awaiting analysis'}</span><StatusBadge label={c.status==='passed_with_help'?'Demonstrated with help':undefined} kind={passed(c)?'verified':c.status==='unavailable'?'unavailable':c.status==='needs_followup'?'needs-followup':'needs-explanation'}/></div><FilePath path={c.snapshot.files?.[0]?.path || 'Source context expired'}/></div><span className="text-[13px] text-secondary">{dateTime(c.created)}</span><ChevronRight size={18} className="text-secondary"/></button>)}</div>}
        <footer className="flex items-center gap-1.5 border-t border-subtle pt-5 text-[13px] text-secondary"><Lock size={14}/> Private to you</footer>
      </div>}
    </main></div>
}

function Evidence({cp,...p}:Props & {cp:Checkpoint}) {
  return <div className="space-y-6"><button onClick={()=>p.navigate('/history')} className="inline-flex items-center gap-1.5 text-[13px] text-secondary hover:text-primary"><ArrowLeft size={16}/> Today’s session</button><div className="flex flex-wrap items-center gap-3"><h1 className="text-[28px] font-semibold leading-[36px]">{cp.question?.concept || 'Awaiting analysis'}</h1><StatusBadge label={cp.status==='passed_with_help'?'Demonstrated with help':undefined} kind={passed(cp)?'verified':'needs-explanation'}/></div><p className="text-[14px] text-secondary">{dateTime(cp.created)} · This result covers the captured code shown below. Provenance: {cp.snapshot.provenance}.</p>{cp.snapshot.partial&&<InlineNotice kind="pending">Partial coverage: source was bounded to the selected excerpt.</InlineNotice>}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,44fr)_minmax(0,56fr)]"><div className="min-w-0 space-y-3 lg:sticky lg:top-20 lg:self-start">{cp.snapshot.files?.length?cp.snapshot.files.map(f=><CodePlain key={f.path} file={f.path} capturedAt={dateTime(cp.created)} code={f.lines.map(l=>`${l.number}  ${l.text}`).join('\n')}/>):<CodeUnavailable file="Expired source"/>}<p className="break-all font-mono text-[11px] text-secondary">Snapshot: {cp.snapshot_hash}</p></div><div className="min-w-0 space-y-5"><EvidenceSection label="Initial question">{cp.question?.question || 'Generation unavailable. Retry from the checkpoint.'}</EvidenceSection>{cp.practice_question&&<EvidenceSection label="Practice question">{cp.practice_question.question}</EvidenceSection>}{cp.attempts.map((a,i)=><div className="space-y-4" key={a.id}><EvidenceSection label={`${cp.practice_started_version && a.version>=cp.practice_started_version?'Practice answer':'Original answer'} ${i+1}`} muted>{a.answer}</EvidenceSection>{a.evaluation?<><EvidenceSection label="Feedback">{a.evaluation.feedback}</EvidenceSection>{a.evaluation.next_question&&<EvidenceSection label="Follow-up question">{a.evaluation.next_question}</EvidenceSection>}</>:<InlineNotice kind="pending">{a.state==='failed'?'Operational failure; explanation preserved for retry.':'Evaluation pending; refresh to reconcile.'}</InlineNotice>}</div>)}
      {passed(cp)?<><div className="rounded-[var(--radius-panel)] border border-success/30 bg-success/10 p-4"><div className="mb-1.5 flex items-center gap-1.5 text-[13px] font-medium text-success"><Check size={15}/> {cp.status==='passed_with_help'?'Demonstrated with help':'Demonstrated reasoning'}</div><p className="text-[14px] leading-[22px]">{cp.attempts.filter(a=>a.evaluation).at(-1)?.evaluation?.feedback}</p></div>{p.config?.capabilities.receipts&&<Card title="Verifiable assessment receipt"><p className="mb-3 text-[13px] text-secondary">Optional anchored evidence on Solana Devnet. This records an assessment, not universal mastery.</p><Button variant="secondary" onClick={()=>p.onReceipt(cp)}>Create verifiable receipt</Button></Card>}{p.config?.capabilities.github && cp.snapshot.pr_import_id&&<Button variant="secondary" onClick={()=>p.onSummary(cp)}>Prepare PR summary</Button>}</>:<Button onClick={()=>p.onCheckpoint(cp)}>Open checkpoint</Button>}
      {cp.learning_explanation&&<EvidenceSection label="Model explanation viewed (help)"><span className="whitespace-pre-wrap">{cp.learning_explanation}</span></EvidenceSection>}
      <p className="text-[12px] text-secondary">Evaluator: {cp.attempts.filter(a=>a.evaluation).at(-1)?.evaluation?.model || cp.model} · Rubric v1 · {cp.explanation_viewed?'Model explanation viewed':cp.status==='passed_with_help'?'Assisted':'Unaided'} explanation</p>
    </div></div></div>
}
function EvidenceSection({label,children,muted}:{label:string;children:ReactNode;muted?:boolean}) {return <div><div className="mb-1.5 text-[12px] font-medium uppercase tracking-wide text-secondary">{label}</div><p className={`whitespace-pre-wrap break-words text-[14px] leading-[22px] ${muted?'rounded-[var(--radius-panel)] border border-subtle bg-panel p-3.5':''}`}>{children}</p></div>}
function Card({title,children}:{title:string;children:ReactNode}) {return <section className="rounded-[var(--radius-panel)] border border-subtle bg-panel p-5"><h2 className="mb-3 text-[15px] font-semibold">{title}</h2>{children}</section>}
function SettingsView(p:Props) {
  const [confirm,setConfirm]=useState(false)
  const [message,setMessage]=useState('')
  const [scope,setScope]=useState(p.project?.scope.join(', ')||'')
  const [exclusions,setExclusions]=useState(p.project?.exclusions.join(', ')||'')
  const [saving,setSaving]=useState(false)
  useEffect(()=>{setScope(p.project?.scope.join(', ')||'');setExclusions(p.project?.exclusions.join(', ')||'')},[p.project?.id,p.project?.scope_hash])
  return <div className="mx-auto max-w-[720px] space-y-6"><button onClick={()=>p.navigate('/history')} className="inline-flex items-center gap-1.5 text-[13px] text-secondary"><ArrowLeft size={16}/> Back to session</button><h1 className="text-[28px] font-semibold leading-[36px]">Project scope &amp; privacy</h1><Card title="Source files in scope"><ul className="divide-y divide-[color:var(--border-subtle)]">{p.project?.scope.map(f=><li key={f} className="flex items-center justify-between py-2.5"><FilePath path={f}/><span className="text-[12px] text-secondary">Included</span></li>)}</ul><p className="mt-3 text-[13px] text-secondary">Excluded: environment files, secrets, ignored files, dependencies, generated output, binaries{p.project?.exclusions.length?', '+p.project.exclusions.join(', '):''}. Update future capture permissions below.</p></Card>
    {p.project&&<Card title="Update capture scope"><div className="space-y-3"><label className="block text-[13px]">Included paths (comma separated)<input className="mt-1 block w-full rounded border border-control bg-canvas p-2" value={scope} onChange={e=>setScope(e.target.value)}/></label><label className="block text-[13px]">Excluded paths (comma separated)<input className="mt-1 block w-full rounded border border-control bg-canvas p-2" value={exclusions} onChange={e=>setExclusions(e.target.value)}/></label><p className="text-[12px] text-secondary">Changes apply to future captures. Existing approved evidence remains private under the retention policy.</p><Button loading={saving} disabled={!scope.trim()} onClick={async()=>{setSaving(true);try{await api(`/v1/projects/${p.project!.id}/scope`,'POST',{name:p.project!.name,scope:scope.split(',').map(x=>x.trim()).filter(Boolean),exclusions:exclusions.split(',').map(x=>x.trim()).filter(Boolean),expected_scope_hash:p.project!.scope_hash});setMessage('Scope saved.');p.refresh()}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}}>Save settings</Button></div></Card>}
    <Card title="Connected services">{Object.entries(p.config?.capabilities||{}).filter(([k,v])=>k!=='managed_ai'&&(k!=='receipts'||v)).map(([name,enabled])=><div key={name} className="flex flex-wrap items-center justify-between gap-3 border-b border-subtle py-3"><span className="text-[14px] capitalize">{name}</span><StatusBadge kind={enabled?'verified':'unavailable'} label={name==='voice'||name==='github'?'Disabled in local edition':enabled?(name==='assessment'?`Local: ${p.config?.ai?.model || 'model ready'}`:'Configured - checked on use'):'Not configured'}/></div>)}{p.config?.capabilities.github&&<div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" onClick={p.onImport}>Review a PR</Button><Button variant="text" onClick={async()=>{try{await api('/v1/github/connection','DELETE');setMessage('GitHub disconnected. Existing remote comments remain.')}catch(e){setMessage((e as Error).message)}}}>Unlink GitHub</Button></div>}{message&&<p role="status" className="mt-3 text-[13px]">{message}</p>}</Card>
    <Card title="AI provider & privacy"><InlineNotice kind="info">Questions, explanations and Managed Ask AI use the local Ollama model on this computer. No API keys, subscriptions or credits are required. Hosted voice, GitHub publication and telemetry are disabled.</InlineNotice><p className="mt-3 text-[13px] text-secondary">Raw source context expires after 30 days when the retention job runs. Submitted explanations remain until you delete the project. A passed checkpoint is evidence about one captured change.</p></Card>
    <Card title="Danger zone"><p className="mb-3 text-[13px] leading-5 text-secondary">Delete this project and its private history. Public chain records and previously published PR comments cannot be removed by this action.</p>{!confirm?<Button variant="destructive" disabled={!p.project} onClick={()=>setConfirm(true)}><Trash size={14}/> Delete project history</Button>:<div className="flex flex-wrap gap-2"><Button variant="destructive" loading={p.busy} onClick={p.onDelete}>Permanently delete {p.project?.name}</Button><Button variant="secondary" onClick={()=>setConfirm(false)}>Keep history</Button></div>}</Card>
  </div>
}
