// C01-C03 and G01-G02 retain the Make export's secondary-dialog styling.
// All status changes below come from the server or wallet; none are timers or fixtures.
import { useState } from 'react'
import { Button, InlineNotice, Modal, TextArea, StatusBadge, FilePath } from './ui'
import { api, type Checkpoint, type Project } from '../lib/api'
import { X, ArrowLeft } from '../lib/icons'

type Receipt = {id:string;state:string;digest:string;public_memo:string;issuer:string;subject:string;network:string;signature:string|null;disclosure:string;revocation:string}
function Header({title,onClose}:{title:string;onClose:()=>void}) {return <div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-[18px] font-semibold">{title}</h2><button aria-label="Close dialog" onClick={onClose} className="rounded p-1 text-secondary"><X size={18}/></button></div>}
function Row({label,value}:{label:string;value:string}) {return <div className="grid gap-1 border-b border-subtle py-2 text-[13px] sm:grid-cols-[130px_minmax(0,1fr)]"><span className="text-secondary">{label}</span><span className="break-all font-mono">{value}</span></div>}
function download(value:unknown,name:string) {const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function ReceiptFlow({checkpoint,onClose,onOpenVerifier}:{checkpoint:Checkpoint;onClose:()=>void;onOpenVerifier:()=>void}) {
  const [receipt,setReceipt]=useState<Receipt|null>(null);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function prepare(){
    const wallet=(window as any).solana
    if(!wallet?.connect || !wallet?.signMessage)throw Error('Use a Solana test wallet browser extension with message signing. Your learning pass is unaffected.')
    const connected=await wallet.connect();const subject=connected.publicKey.toString()
    const challenge=await api('/v1/wallet-challenges','POST',{checkpoint_id:checkpoint.id,subject})
    const signed=await wallet.signMessage(new TextEncoder().encode(challenge.message),'utf8')
    const signature=btoa(String.fromCharCode(...new Uint8Array(signed.signature)))
    setReceipt(await api('/v1/receipts/preview','POST',{checkpoint_id:checkpoint.id,subject,challenge_id:challenge.challenge_id,signature}))
  }
  return <Modal onClose={onClose} wide><Header title="Create an assessment receipt" onClose={onClose}/><div className="space-y-4"><InlineNotice kind="info">Solana Devnet · Demo network. Optional anchored evidence of this assessment; it does not independently prove mastery.</InlineNotice><p className="text-[13px] text-secondary">{checkpoint.question?.concept} · Your passed checkpoint and managed AI access do not depend on this action.</p>{error&&<div role="alert"><InlineNotice kind="error">{error}</InlineNotice></div>}
    {!receipt?<><p className="text-[13px] text-secondary">Connect a test wallet and sign a fresh challenge to prove control for this preview. The wallet signature does not transfer funds.</p><Button loading={busy} onClick={()=>void run(prepare)}>Connect test wallet &amp; prepare preview</Button></>:<><Row label="State" value={receipt.state}/><Row label="Issuer" value={receipt.issuer||'Evidence expired'}/><Row label="Subject wallet" value={receipt.subject||'Evidence expired'}/><div className="rounded-[var(--radius-panel)] border border-subtle bg-canvas p-3"><p className="mb-2 text-[12px] font-medium uppercase tracking-wide text-secondary">Exact on-chain memo</p><code className="break-all text-[13px]">{receipt.public_memo}</code></div><p className="text-[13px] leading-5 text-secondary">{receipt.disclosure}</p><InlineNotice kind="pending">{receipt.revocation}</InlineNotice>
      {receipt.state==='awaiting_consent'?<><label className="flex items-start gap-2 text-[13px]"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 accent-[var(--action-primary)]"/>I approve this exact memo and public issuer transaction metadata on Devnet.</label><Button loading={busy} disabled={!consent} onClick={()=>void run(async()=>setReceipt(await api('/v1/receipts','POST',{preview_id:receipt.id,approved_digest:receipt.digest,consent:true})))}>Issue Devnet receipt</Button></>:<>{receipt.signature&&<Row label="Transaction" value={receipt.signature}/>}<div className="flex flex-wrap gap-2">{receipt.state!=='confirmed'&&<Button loading={busy} variant="secondary" onClick={()=>void run(async()=>setReceipt(await api(`/v1/receipts/${receipt.id}/reconcile`,'POST')))}>Reconcile transaction</Button>}<Button variant="secondary" onClick={()=>void run(async()=>download(await api(`/v1/receipts/${receipt.id}/export`),`beprogram-${receipt.id}.json`))}>Export private evidence package</Button><Button variant="text" onClick={onOpenVerifier}>Open independent verifier</Button></div></>}
    </>}</div></Modal>
}

export function VerifierPage({onBack}:{onBack:()=>void}) {
  const [text,setText]=useState('');const [result,setResult]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  return <div className="mx-auto max-w-[880px] space-y-5 rounded-[var(--radius-dialog)] border border-subtle bg-panel p-5 sm:p-8"><button onClick={onBack} className="flex items-center gap-2 text-[13px] text-secondary"><ArrowLeft size={16}/> Back to history</button><h1 className="text-[28px] font-semibold leading-[36px]">Verify an assessment receipt</h1><p className="text-[14px] leading-[22px] text-secondary">This verifier calculates the supplied package digest and reads Solana Devnet directly. It does not use BeProgram history or receipt status as proof. Issuer trust comes from the server’s configured allowlist. For an independent deployment, use the included CLI with an issuer you trust.</p><label className="block text-[13px]">Load exported package<input className="mt-2 block max-w-full" type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(f&&f.size<=250000){setText(await f.text());setResult(null)}else setError('Choose an evidence package under 250 KB.')}}/></label><TextArea label="Evidence package JSON" value={text} onChange={e=>{setText(e.target.value);setResult(null)}} className="min-h-[200px] font-mono"/><Button loading={busy} disabled={!text.trim()} onClick={async()=>{setBusy(true);setError('');setResult(null);try{const p=JSON.parse(text);setResult(await api('/v1/verify','POST',{manifest:p.manifest,signature:p.signature}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Verify against Devnet</Button>{error&&<div role="alert"><InlineNotice kind="error">{error}</InlineNotice></div>}{result&&<div className="space-y-3" role="status"><Row label="Result" value={result.status}/><Row label="Network" value={result.network}/><Row label="Issuer" value={result.issuer_verified?'issuer_verified':'Not verified'}/><Row label="Evidence" value={result.evidence_matches?'evidence_matches':'Not verified'}/><Row label="Current subject control" value="Not verified — requires a fresh verifier wallet challenge"/><InlineNotice kind="pending">{result.revocation}. {result.subject_note}</InlineNotice></div>}</div>
}

export function PRImportDialog({project,onClose,onImport}:{project:Project;onClose:()=>void;onImport:(files:any)=>void}) {
  const [repository,setRepo]=useState('');const [number,setNumber]=useState('');const [link,setLink]=useState('');const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Modal onClose={onClose} wide><Header title="Review a GitHub pull request" onClose={onClose}/><div className="space-y-4"><p className="text-[13px] text-secondary">Composio retrieves only the selected PR and eligible files in {project.name}’s approved scope. Choose the GitHub permissions shown during connection.</p><Button variant="secondary" loading={busy} onClick={()=>void run(async()=>{const r=await api('/v1/github/connect','POST');setLink(r.redirect_url)})}>Connect GitHub account</Button>{link&&<a href={link} target="_blank" rel="noreferrer" className="block text-[13px] text-action underline">Authorize GitHub, then return here</a>}
    <label className="block text-[13px]">Repository (owner/name)<input value={repository} onChange={e=>{setRepo(e.target.value);setResult(null)}} className="mt-1 block w-full rounded border border-control bg-canvas p-2"/></label><label className="block text-[13px]">Pull request number<input type="number" min={1} value={number} onChange={e=>{setNumber(e.target.value);setResult(null)}} className="mt-1 block w-full rounded border border-control bg-canvas p-2"/></label><Button loading={busy} disabled={!repository||!number} onClick={()=>void run(async()=>setResult(await api('/v1/github/import','POST',{project_id:project.id,repository,number:Number(number)})))}>Import selected PR context</Button>
    {error&&<div role="alert"><InlineNotice kind="error">{error}</InlineNotice></div>}{result&&<><Row label="Repository" value={result.repository}/><Row label="PR" value={'#'+result.number+' '+result.title}/><Row label="Base SHA" value={result.base}/><Row label="Frozen head SHA" value={result.head}/><div className="space-y-2">{result.included_files.map((f:string)=><div key={f}><FilePath path={f}/></div>)}</div>{result.partial&&<InlineNotice kind="pending">Only files within the approved project scope are included.</InlineNotice>}<Button onClick={()=>onImport(result.capture)}>Review capture before assessment</Button></>}
  </div></Modal>
}

export function PRSummaryDialog({checkpoint,onClose}:{checkpoint:Checkpoint;onClose:()=>void}) {
  const [preview,setPreview]=useState<any>(null);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Modal onClose={onClose} wide><Header title="Publish a comprehension summary" onClose={onClose}/><div className="space-y-4"><p className="text-[13px] text-secondary">Only the selected passed checkpoint is included. Raw answers, retry history and source code are excluded. Publishing does not approve or merge the PR.</p>{!preview?<Button loading={busy} onClick={()=>void run(async()=>setPreview(await api('/v1/publications/preview','POST',{checkpoint_ids:[checkpoint.id]})))}>Prepare exact preview</Button>:<><Row label="Repository" value={preview.repository}/><Row label="Pull request" value={'#'+preview.number}/><Row label="Reviewed head" value={preview.head}/><pre className="max-h-[320px] overflow-auto whitespace-pre-wrap break-words rounded-[var(--radius-panel)] border border-subtle bg-canvas p-3 font-mono text-[12px] leading-5">{preview.body}</pre>{preview.state==='published'?<><StatusBadge kind="verified" label="Published"/><a href={preview.result.url} target="_blank" rel="noreferrer" className="block break-all text-[13px] text-action underline">{preview.result.url}</a></>:<><label className="flex gap-2 text-[13px]"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I approve this exact comment and destination.</label><Button loading={busy} disabled={!consent} onClick={()=>void run(async()=>setPreview(await api('/v1/publications','POST',{preview_id:preview.id,approved_digest:preview.digest,consent:true})))}>Publish or reconcile approved comment</Button></>}</>}{error&&<div role="alert"><InlineNotice kind="error">{error}</InlineNotice></div>}</div></Modal>
}
