import { test, expect } from '@playwright/test'
const token='automated-test-only-token-not-a-real-secret'
const good='The query structure is fixed. The driver binds email as data, so quotes in email cannot change SQL syntax. Input validation is still needed for business rules.'
const capture={files:[{path:'src/data/findUser.ts',before:'export async function findUser(db, email) {\n  return db.query(`SELECT * FROM users WHERE email = "${email}"`);\n}',after:'export async function findUser(db, email) {\n  return db.query("SELECT * FROM users WHERE email = $1", [email]);\n}'}],provenance:'user_reported_manual',idempotency_key:'browser-capture-01'}

test('browser: real API persistence, follow-up, pass and managed gate; desktop/mobile visual checks',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  await page.getByLabel('Local development token').fill(token)
  await page.getByRole('button',{name:'Connect account',exact:true}).click()
  await page.getByRole('button',{name:'New project',exact:true}).click()
  await page.getByLabel('Project name').fill('campus-events')
  await page.getByLabel('Included paths').fill('src')
  await page.getByRole('button',{name:'Create project',exact:true}).click()
  await page.getByRole('button',{name:'Start session',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Session active'})).toBeVisible()
  await page.getByRole('button',{name:'Review current changes',exact:true}).click()
  await page.getByLabel('Approved capture JSON').fill(JSON.stringify(capture))
  await page.getByRole('button',{name:'Approve capture and generate question'}).click()
  await expect(page.getByRole('heading',{name:'SQL parameterization'})).toBeVisible()
  await page.screenshot({path:'test-results/desktop-checkpoint.png',fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.screenshot({path:'test-results/mobile-checkpoint.png',fullPage:true,animations:'disabled'})
  await page.getByLabel('Your explanation',{exact:true}).fill('It makes the database safer.')
  await page.getByRole('button',{name:'Submit explanation',exact:true}).click()
  await expect(page.getByRole('heading',{name:'One detail to clarify'})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading',{name:'One detail to clarify'})).toBeVisible()
  await page.getByLabel('Your follow-up answer').fill(good)
  await page.getByRole('button',{name:'Submit follow-up',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Understanding verified'})).toBeVisible()
  await expect(page.getByText('Saved to your learning history.')).toBeVisible()
  await page.getByRole('button',{name:'Continue coding',exact:true}).click()
  await page.getByRole('button',{name:'Send AI request',exact:true}).click()
  await page.getByLabel('Coding request').fill('Write a safe helper')
  await page.getByRole('dialog').getByRole('button',{name:'Send AI request',exact:true}).click()
  await expect(page.getByText('Test-only coding assistant response.')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.goto('/history')
  await expect(page.getByText('concepts demonstrated')).toContainText('1')
  await page.getByRole('button').filter({hasText:'SQL parameterization'}).click()
  await expect(page.getByText(good,{exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.screenshot({path:'test-results/mobile-evidence.png',fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:1440,height:1000})
  await page.screenshot({path:'test-results/desktop-evidence.png',fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'Toggle theme'}).click()
  await page.screenshot({path:'test-results/light-evidence.png',fullPage:true,animations:'disabled'})
  expect(errors).toEqual([])
  const history=await request.get('/v1/history',{headers:{Authorization:'Bearer '+token}})
  const saved=await history.json();expect(saved[0].attempts).toHaveLength(2);expect(saved[0].status).toBe('passed')
  await page.goto('/settings')
  await page.getByLabel('Excluded paths (comma separated)').fill('src/private')
  await page.getByRole('button',{name:'Save settings',exact:true}).click()
  await expect(page.getByText('Scope saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Excluded paths (comma separated)')).toHaveValue('src/private')
  await expect(page.getByText('Not configured',{exact:true})).toHaveCount(4)
})

test('unconfigured optional services are honest and verifier works without login',async({page})=>{
  await page.goto('/verify')
  await expect(page.getByRole('heading',{name:'Verify an assessment receipt'})).toBeVisible()
  await page.getByLabel('Evidence package JSON').fill(JSON.stringify({manifest:{schema:'beprogram.assessment.v1',network:'devnet',issuer:'untrusted'},signature:'a'.repeat(88)}))
  await page.getByRole('button',{name:'Verify against Devnet'}).click()
  await expect(page.getByText('unknown_issuer',{exact:true})).toBeVisible()
  await expect(page.getByText('Not verified',{exact:true})).toHaveCount(2)
})
