import { test, expect } from '@playwright/test'

test('projects: create, cancel deletion, recover from failure, delete active project and preserve another', async ({ page, request }) => {
  const headers = { Authorization: 'Bearer automated-test-only-token-not-a-real-secret' }
  const priorSessions = await (await request.get('/v1/sessions', { headers })).json()
  for (const session of priorSessions) {
    if (session.status === 'active') await request.post(`/v1/sessions/${session.id}/end`, { headers })
  }
  const create = async (name: string) => (await request.post('/v1/projects', { headers, data: { name, scope: ['src'], exclusions: [] } })).json()
  const active = await create('Active project to remove')
  const kept = await create('Project to keep')
  const started = await request.post('/v1/sessions', { headers, data: { project_id: active.id } })
  expect(started.ok()).toBeTruthy()
  await page.goto('/projects')
  await page.getByLabel('Local development token').fill('automated-test-only-token-not-a-real-secret')
  await page.getByRole('button', { name: 'Connect account', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Manage projects' })).toBeVisible()
  const row = page.getByRole('article', { name: active.name, exact: true })
  await expect(row.getByText('Session active')).toBeVisible()
  await page.getByRole('button', { name: 'New project', exact: true }).click()
  await page.getByLabel('Project name').fill('Created from projects page')
  await page.getByRole('button', { name: 'Create project', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Created from projects page', exact: true })).toBeVisible()
  await expect(row.getByText('Session active')).toBeVisible()
  await row.getByRole('button', { name: 'Delete project', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Your code files and folders stay on your computer')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(row).toBeVisible()
  await page.route(`**/v1/projects/${active.id}`, route => route.request().method() === 'DELETE' ? route.fulfill({ status: 503, json: { message: 'Temporary test failure' } }) : route.continue())
  await row.getByRole('button', { name: 'Delete project', exact: true }).click()
  await page.getByRole('button', { name: 'Permanently delete project', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
  await page.unroute(`**/v1/projects/${active.id}`)
  await page.getByRole('button', { name: 'Permanently delete project', exact: true }).click()
  await expect(row).toHaveCount(0)
  await page.reload()
  await expect(row).toHaveCount(0)
  await expect(page.getByRole('article', { name: kept.name, exact: true })).toBeVisible()
  const sessions = await (await request.get('/v1/sessions', { headers })).json()
  expect(sessions.some((s: { project_id: string }) => s.project_id === active.id)).toBe(false)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: 'test-results/projects-mobile.png', fullPage: true })
})
